package turtle.demo;

import java.awt.Color;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

import turtle.Turtle;
import turtle.TurtleCanvas;

/**
 * Displays an approximation of the Mandelbrot Set using the Turtle library.
 *
 * The image is generated by mapping points on the TurtleCanvas to complex
 * numbers and testing whether the sequence
 *
 *     z(n+1) = z(n)^2 + c
 *
 * remains bounded.
 *
 * Points that appear to belong to the Mandelbrot Set are drawn in black.
 *
 * This demo deliberately uses speed(0) because rendering the set requires
 * thousands of movements. Animating each individual movement would take
 * a very long time.
 */
public class MandelbrotDemo {

    /**
     * Width and height of the region drawn on the 600 x 600 TurtleCanvas.
     */
    private static final int DRAW_WIDTH = 540;
    private static final int DRAW_HEIGHT = 430;

    /**
     * Sampling distance in Turtle coordinate units.
     *
     * Smaller values create a more detailed image but require more work.
     *
     * Try:
     *   4.0 = fast, coarse
     *   3.0 = good starting point
     *   2.0 = more detailed
     *   1.0 = much more detailed, but substantially more expensive
     */
    private static final double STEP = 3.0;

    /**
     * Maximum number of iterations used when deciding whether a point
     * belongs to the Mandelbrot Set.
     *
     * Higher values improve boundary detail but require more computation.
     */
    private static final int MAX_ITERATIONS = 100;

    /**
     * Region of the complex plane to display.
     *
     * The Mandelbrot Set is mostly contained within:
     *
     *     real:      -2.0 to 1.0
     *     imaginary: -1.2 to 1.2
     */
    private static final double MIN_REAL = -2.0;
    private static final double MAX_REAL = 1.0;

    private static final double MIN_IMAGINARY = -1.2;
    private static final double MAX_IMAGINARY = 1.2;


    public static void main(String[] args) {

        SwingUtilities.invokeLater(() -> {

            // ------------------------------------------------------------
            // Create the Turtle model.
            // ------------------------------------------------------------

            Turtle turtle = new Turtle();

            /*
             * Mandelbrot rendering requires many movements.
             *
             * Use speed 0 so the completed image is displayed immediately
             * rather than animating thousands of individual movements.
             */
            turtle.speed(0);

            // Draw the Mandelbrot Set.
            drawMandelbrot(turtle);

            /*
             * Create the canvas AFTER generating the image.
             *
             * Because all movements already exist when TurtleCanvas is
             * constructed, the canvas treats them as completed movements
             * and displays the entire set immediately.
             */
            TurtleCanvas canvas = new TurtleCanvas(turtle);

            // ------------------------------------------------------------
            // Create the Swing window.
            // ------------------------------------------------------------

            JFrame frame = new JFrame("Mandelbrot Set - Turtle Graphics");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

            frame.add(canvas);
            frame.pack();

            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        });
    }


    /**
     * Generates and draws the Mandelbrot Set.
     *
     * Instead of drawing every individual sample as a tiny point, this
     * method combines neighboring Mandelbrot points into horizontal runs.
     *
     * Each run is rendered as one Turtle line segment. This greatly reduces
     * the number of LineSegment objects required.
     */
    private static void drawMandelbrot(Turtle turtle) {

        // Draw the set in black.
        turtle.penColor(Color.BLACK);

        /*
         * Give each horizontal run enough thickness to cover approximately
         * one sampling row.
         */
        turtle.penWidth(STEP);

        /*
         * Scan the image from top to bottom.
         *
         * Turtle coordinates use positive Y upward, so the first row starts
         * at positive DRAW_HEIGHT / 2.
         */
        for (
            double screenY = DRAW_HEIGHT / 2.0;
            screenY >= -DRAW_HEIGHT / 2.0;
            screenY -= STEP
        ) {

            boolean insideRun = false;
            double runStartX = 0;

            /*
             * Scan one row from left to right.
             */
            for (
                double screenX = -DRAW_WIDTH / 2.0;
                screenX <= DRAW_WIDTH / 2.0;
                screenX += STEP
            ) {

                /*
                 * Convert the TurtleCanvas coordinate into a point
                 * in the complex plane.
                 */
                double real = map(
                    screenX,
                    -DRAW_WIDTH / 2.0,
                    DRAW_WIDTH / 2.0,
                    MIN_REAL,
                    MAX_REAL
                );

                double imaginary = map(
                    screenY,
                    -DRAW_HEIGHT / 2.0,
                    DRAW_HEIGHT / 2.0,
                    MIN_IMAGINARY,
                    MAX_IMAGINARY
                );

                // Determine whether this point appears to be in the set.
                boolean inside =
                    isInMandelbrotSet(
                        real,
                        imaginary,
                        MAX_ITERATIONS
                    );


                // --------------------------------------------------------
                // Start a horizontal run.
                // --------------------------------------------------------

                if (inside && !insideRun) {
                    insideRun = true;
                    runStartX = screenX;
                }


                // --------------------------------------------------------
                // Finish a horizontal run.
                // --------------------------------------------------------

                if (!inside && insideRun) {

                    drawHorizontalRun(
                        turtle,
                        runStartX,
                        screenX - STEP,
                        screenY
                    );

                    insideRun = false;
                }
            }


            /*
             * If the row ended while still inside the Mandelbrot Set,
             * finish the final run.
             */
            if (insideRun) {

                drawHorizontalRun(
                    turtle,
                    runStartX,
                    DRAW_WIDTH / 2.0,
                    screenY
                );
            }
        }

        // Leave the turtle at the origin after rendering.
        turtle.penUp();
        turtle.home();
    }


    /**
     * Draws one horizontal portion of the Mandelbrot Set.
     *
     * The turtle moves to the beginning with the pen up and then draws
     * to the end with the pen down.
     */
    private static void drawHorizontalRun(
        Turtle turtle,
        double startX,
        double endX,
        double y
    ) {

        // Move to the beginning without drawing.
        turtle.penUp();
        turtle.goTo(startX, y);

        // Draw the horizontal run.
        turtle.penDown();
        turtle.goTo(endX, y);
    }


    /**
     * Tests whether the supplied complex number appears to belong to
     * the Mandelbrot Set.
     *
     * For the Mandelbrot recurrence:
     *
     *     z(n+1) = z(n)^2 + c
     *
     * z begins at 0.
     *
     * If |z| becomes greater than 2, the sequence will escape to infinity
     * and c is not in the Mandelbrot Set.
     *
     * If it has not escaped after maxIterations, we treat the point as
     * belonging to the set for rendering purposes.
     */
    private static boolean isInMandelbrotSet(
        double cReal,
        double cImaginary,
        int maxIterations
    ) {

        double zReal = 0.0;
        double zImaginary = 0.0;

        for (int i = 0; i < maxIterations; i++) {

            /*
             * Square z:
             *
             * (a + bi)^2
             *
             * =
             *
             * (a^2 - b^2) + (2ab)i
             */
            double nextReal =
                zReal * zReal
                - zImaginary * zImaginary
                + cReal;

            double nextImaginary =
                2.0 * zReal * zImaginary
                + cImaginary;

            zReal = nextReal;
            zImaginary = nextImaginary;


            /*
             * Instead of calculating sqrt(a^2 + b^2), compare the squared
             * magnitude to 4.
             *
             * |z| > 2
             *
             * is equivalent to:
             *
             * real^2 + imaginary^2 > 4
             */
            double magnitudeSquared =
                zReal * zReal
                + zImaginary * zImaginary;

            if (magnitudeSquared > 4.0) {
                return false;
            }
        }

        return true;
    }


    /**
     * Maps a value from one numerical interval into another.
     *
     * For example, this converts Turtle screen coordinates into
     * coordinates on the complex plane.
     */
    private static double map(
        double value,
        double sourceMin,
        double sourceMax,
        double destinationMin,
        double destinationMax
    ) {

        double fraction =
            (value - sourceMin)
            / (sourceMax - sourceMin);

        return destinationMin
            + fraction
            * (destinationMax - destinationMin);
    }
}